feature_extract_enable : 0
pyr: 3
init_num: 100
linethre3d: 0.2
linethre3d_proj: 10.0
linethre2d: 10.0
lamda: 0.03
line_threshold: 10
max_iteration : 10
dense_map_enable : 1
cut_points_above_ground: false
grid_pts_num: 1
filter_size_surf : 0.15
filter_size_map : 0.3
filter_size: 0.5
down_sample_manner: 1
down_sample_num: 1000
cube_side_length : 20
debug : 0
img_scale : 1.0
grid_size : 40
patch_size : 8
depth_search_radius: 60
theta_thre: 0.8
delta_dist_thre: 0.5
skip_depth: 8.0
img_enable : 1
lidar_enable : 1
equalize: true
trans_thre: 0.1
rot_thre: 0.1309
enable_undistort: false
outlier_threshold : 1200 # 
score_threshold: 10.0
edgescore_threshold: 4.0
ncc_en: true
ncc_thre: 0.8
window_size : 20
pure_imu: false
img_point_cov : 100000.0 # 1000
line_cov : 100.0 # 1000
projection_point_cov: 100000.0
triangulate_point_cov: 100.0
enable_projection: true
enable_triangulate: true
enable_line: true
enable_lidar: true
laser_point_cov : 0.001 #
enable_undistort: false 
convert_map: true
mapextR: [-1,0,0,
            0,1,0,
            0,0,-1]
mapextT: [0,0,0]

read_enable: true
pub_pcl: true
encoding: "mono8"
map_dir: "/home/weilin/VIOLM/src/VIOLM/map/sbs_02.pcd"
path_file: "path/sbs_02.txt"
lines_file: "lines/sbs_02.txt"
t_shift: -0.0199575325817

origin_pose: [0.0,0,0.0,3.1415926,0,3.1415926]

common:
    lid_topic:  "/os1_cloud_node1/points"
    imu_topic:  "/os1_cloud_node1/imu"

mapping:
    normalized: false
    acc_cov_scale: 100
    gyr_cov_scale: 10000
    acc_Q_scale: 10
    gyr_Q_scale: 10
    fov_degree: 90
    filter_size_surf_min: 0.5
    extrinsic_T: [0,0,0]
    extrinsic_R: [1,0,0,
    0,1,0,
    0,0,1]

camera:
    img_topic: /left/image_raw
    # NTU_VIRAL
    Rci: [0.02183084,  0.99975965, -0.00201407,
       -0.01312053,  0.00230088,  0.99991128,
       0.99967558, -0.02180248,  0.01316761,]
    Pci: [0.122993,  0.0398643, -0.0577101]
    blind: 2.5

preprocess:
    lidar_type: 3                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 
    scan_line: 16
    scan_rate: 10                # only need to be set for velodyne, unit: Hz,
    blind: 4.5
    point_filter_num : 4
    feature_extract_enable : 0
